services:
    db:
      image: postgres:12.6-alpine
      restart: always
      ports:
        - "15432:5432"
      environment:
        DEBUG: 1
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "hoge"
        POSTGRES_PASSWORD: "hogehoge"
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
        TZ: Asia/Tokyo
      volumes:
        - ./dbdata/pgdata:/var/lib/postgresql/data
        - ./dbentry:/docker-entrypoint-initdb.d